apiVersion: v1
kind: Namespace
metadata:
  name: meta-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krm-backend
  namespace: meta-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krm-backend
  namespace: meta-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: krm-backend
    namespace: meta-namespace