apiVersion: v1
kind: Service
metadata:
  name: krm-backend
spec:
  selector:
    app: krm-backend  # 必须匹配Pod的标签
  ports:
    - protocol: TCP
      port: 8080   # 服务暴露端口
      targetPort: 8080  # Pod上的端口